name: Update My TRMNL
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history to make merging easier
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow beautifulsoup4 cloudscraper
          
      - name: Run the update
        env:
          TRMNL_API_KEY: ${{ secrets.TRMNL_API_KEY }}
        run: python update_image.py
          
      - name: Save Image to Repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add display.png
          git commit -m "Update Fortnite Image" || exit 0
          git pull origin main --rebase --autostash
          git push origin main
